### ISSUE TITLE
plan approved

### ISSUE THREAD

**Issue by hackers-test** [ttl2132/bio-minigame#1]
Hi Tian, 

This sounds like a good plan. I sounds like you will likely spend most of your time on the kivy aspect of it in terms of designing the GUI, and writing code to handle the touch i/o aspects. That should be fun.

### Ideas for extending

- You could create a back-end server API for your game running on heroku that keeps a SQL database to store the global best records. This way any user that plays will be able to compete against any other player and the scores update instantly.

- Exploring kivy sounds great, and if you have time it would be great to see you publish it as a mobile app. 

- Do you have a specific concept or class topic in mind to focus on? Example, anatomy class at Columbia? Or Organic chemistry? The latter might be very extendible in terms of being able to write functions that could randomly generate molecules according to some generative function.

**Comment by ttl2132** [comment]
Back-end API and modularity of program addressed in proposal.
